--- #YAML:1.0
name:               Parse-Log-Smbd
version:            0.02
abstract:           parse log.smbd files to fetch usernames and connections to network shares
author:
    - Ari Constancio <affc@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Devel::CheckOS:  0
    IO::File:        0
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
